steps:

# pull nginx build cache
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull asia.gcr.io/$PROJECT_ID/nginx:latest || exit 0

# pull nginx build cache
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull asia.gcr.io/$PROJECT_ID/app:latest || exit 0

# build & push nginx docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t',
            'asia.gcr.io/$PROJECT_ID/nginx:$BUILD_ID',
            '--cache-from', 'asia.gcr.io/$PROJECT_ID/nginx:$BUILD_ID',
            './docker/docker-nginx'
        ]
  id: docker build nginx
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'asia.gcr.io/$PROJECT_ID/nginx:$BUILD_ID' ]
  id: docker push nginx
  waitFor:
  - docker build nginx

# build & push django docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia.gcr.io/$PROJECT_ID/app:$BUILD_ID', './docker/docker-django' ]
  id: docker build app
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'asia.gcr.io/$PROJECT_ID/app:$BUILD_ID' ]
  id: docker push app
  waitFor:
  - docker build app

# gcloud authenthication
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'container', 'clusters', 'get-credentials', 'ohta-k8s-production', '--zone', 'asia-northeast1-a', '--project', '$PROJECT_ID' ]
  id: get-credentials
  waitFor:
  - docker push nginx
  - docker push app

# deploy pods on GKE
- name: 'gcr.io/cloud-builders/kubectl'
  args: [ 'apply', '-k', 'apps-gcp.yaml' ]
  waitFor:
  - get-credentials

timeout: 600s
#options:
# machineType: 'N1_HIGHCPU_8'
tags:
- my-first-blog
- ohtaro
images:
- 'asia.gcr.io/$PROJECT_ID/nginx:latest'
- 'asia.gcr.io/$PROJECT_ID/app:latest'
