steps:

# -----------------------------------------------
# Docker build & push
# -----------------------------------------------
# pull nginx cache
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull asia.gcr.io/$PROJECT_ID/nginx:$BRANCH_NAME || exit 0

# pull app cache
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull asia.gcr.io/$PROJECT_ID/app:$BRANCH_NAME || exit 0

# build nginx docker image from cache
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t',
            'asia.gcr.io/$PROJECT_ID/nginx:$BUILD_ID',
            '--cache-from',
            'asia.gcr.io/$PROJECT_ID/nginx:$BRANCH_NAME',
            './docker/docker-nginx'
        ]
  id: docker build nginx

# push nginx docker image to gcr
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'asia.gcr.io/$PROJECT_ID/nginx:$BUILD_ID' ]
  id: docker push nginx
  waitFor:
  - docker build nginx

# build appx docker image from cache
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t',
            'asia.gcr.io/$PROJECT_ID/app:$BUILD_ID',
            '--cache-from', 'asia.gcr.io/$PROJECT_ID/app:$BRANCH_NAME',
            './docker/docker-django'
        ]
  id: docker build app

# push app docker image to gcr
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'asia.gcr.io/$PROJECT_ID/app:$BUILD_ID' ]
  id: docker push app
  waitFor:
  - docker build app

# Create branch name tag for cache
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'tag',
            'asia.gcr.io/$PROJECT_ID/nginx:$BUILD_ID',
            'asia.gcr.io/$PROJECT_ID/nginx:$BRANCH_NAME'
        ]
  id: branch tag nginx

- name: 'gcr.io/cloud-builders/docker'
  args: [
            'tag',
            'asia.gcr.io/$PROJECT_ID/app:$BUILD_ID',
            'asia.gcr.io/$PROJECT_ID/app:$BRANCH_NAME'
        ]
  id: branch tag app

# push docker image to gcr for cache
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'asia.gcr.io/$PROJECT_ID/nginx:$BRANCH_NAME' ]
  waitFor:
  - branch tag nginx

# push docker image to gcr for cache
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'asia.gcr.io/$PROJECT_ID/app:$BRANCH_NAME' ]
  waitFor:
  - branch tag app

# -----------------------------------------------
# Deploy pods on GKE
# -----------------------------------------------
# gcloud authenthication
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
            'container',
            'clusters',
            'get-credentials',
            'ohta-k8s-production',
            '--zone', 'asia-northeast1-a',
            '--project', '$PROJECT_ID'
        ]
  id: get-credentials
  waitFor:
  - docker push nginx
  - docker push app

# Deploy pods on GEK
- id: deploy
  name: 'gcr.io/$PROJECT_ID/kustomize'
  args:
  - 'edit'
  - 'set'
  - 'image'
  - 'asia.gcr.io/$PROJECT_ID/nginx=asia.gcr.io/$PROJECT_ID/nginx:$BUILD_ID'
  - 'k8s/overlays/prod'
  env:
    - 'APPLY=true'
    - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=ohta-k8s-production',
    - 'GCLOUD_PROJECT=$PROJECT_ID'

# deploy pods on GKE
- name: 'gcr.io/cloud-builders/kubectl'
  args: [ 'version' ]
  waitFor:
  - get-credentials


# build timeout
timeout: 600s

# build tag
tags:
- my-first-blog
- ohtaro

# build image
images:
- 'asia.gcr.io/$PROJECT_ID/nginx:$BRANCH_NAME'
- 'asia.gcr.io/$PROJECT_ID/app:$BRANCH_NAME'

# build machine type
#options:
# machineType: 'N1_HIGHCPU_8'
