version: '3.7'

services:

  web:
    build: ./docker-nginx
    image: asia.gcr.io/soe-trial-oota/nginx:latest
    container_name: frontend
    hostname: frontend
    depends_on:
      - app
      - db
    ports:
      - 80:80
    networks:
      - frontend

  app:
    build: ./docker-django
    image: asia.gcr.io/soe-trial-oota/app:latest
    environment:
      DATADOG_APP_NAME: "my-first-blog"
      DATADOG_APP_ENV: "local"
      DATADOG_TRACE_AGENT_HOSTNAME: "dd-agent"
      DD_AGENT_PORT: "8126"
    container_name: app
    hostname: app
    depends_on:
      - db
    networks:
      - frontend
      - backend

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: blog
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog
    container_name: mysql
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql
    networks:
      - backend


  dd-agent:
    image: datadog/agent:latest
    container_name: dd-agent
    environment:
      DD_API_KEY: "34e0334e1e1c7dadb8b6a4291e6a8cd1"
      DD_APM_ENABLED: "true"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:

volumes:
  mysql:
