apiVersion: skaffold/v1beta8
kind: Config
profiles:

### Production config
- name: prod
  build:
    tagPolicy:
      sha256: {}
    artifacts:
    - image: asia.gcr.io/soe-trial-ohta/app
      context: ./docker/docker-django
    - image: asia.gcr.io/soe-trial-ohta/nginx
      context: ./docker/docker-nginx
    local:
      push: true
      useBuildkit: true
  deploy:
    kustomize:
      path: "./k8s/overlays/production"
      flags:
        apply: ["--validate=false"]

### Development Config
- name: dev
  build:
    tagPolicy:
      sha256: {}
    artifacts:
    - image: asia.gcr.io/soe-trial-ohta/app
      context: ./docker/docker-django
    - image: asia.gcr.io/soe-trial-ohta/nginx
      context: ./docker/docker-nginx
    local:
      push: true
      useBuildkit: true
  deploy:
    kustomize:
      path: "./k8s/overlays/development"
      flags:
        delete: ["--grace-period=0","--force"]

### Local config
- name: local
  build:
    tagPolicy:
      sha256: {}
    artifacts:
    - image: app
      context: ./docker/docker-django
    - image: nginx
      context: ./docker/docker-nginx
    local:
      push: false
      useBuildkit: true
  deploy:
    kustomize:
      path: "./k8s/overlays/local"
      flags:
        delete: ["--grace-period=0","--force"]
