apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# すべてのリソースに設定するnamespace
namespace: blog

# すべてのリソースに追加するlabelとselector
commonLabels:
  app: blog


# kustomizeでビルドする対象ファイル
resources:
- ./deployment.yaml
- ./service.yaml
- ./namespace.yaml

# Image tag change
images:
- name: asia.gcr.io/soe-gcp-development/app
  newTag: ${CIRCLE_SHA1}
- name: asia.gcr.io/soe-gcp-development/frontend
  newTag: ${CIRCLE_SHA1}
