apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# すべてのリソースに設定するnamespace
namespace: blog

# すべてのリソースに追加するlabelとselector
commonLabels:
  app: blog

# kustomizeでビルドする対象ファイル
resources:
- ./namespace.yaml
- ./nginx-deployment.yaml
- ./nginx-service.yaml
- ./app-deployment.yaml
- ./app-service.yaml

images:
- name: asia.gcr.io/soe-gcp-development/frontend
  newTag: latest
- name: asia.gcr.io/soe-gcp-development/app
  newTag: latest
