apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

# すべてのリソースに設定するnamespace
namespace: blog-dev

# すべてのリソースに追加するlabelとselector
commonLabels:
  app: blog

# kustomizeでビルドする対象ファイル
resources:
- mysql-statefulset.yaml
- mysql-service-clusterip.yaml
- mysql-configmap.yaml
- namespace.yaml

images:
- name: app
  newName: asia.gcr.io/soe-trial-ohta/app
- name: nginx
  newName: asia.gcr.io/soe-trial-ohta/nginx

secretGenerator:
- behavior: merge
  env: mysql-db-pass.env
  name: mysql-db-pass
