apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: blog
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
      tier: backend
  template:
    metadata:
      labels:
        app: blog
        tier: backend
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: MYSQL_DATABASE
            value: blog
          - name: MYSQL_USER
            value: blog
          - name: MYSQL_ROOT_PASSWORD
            value: blog
