apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: ingress-backendconfig
spec:
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false
#  securityPolicy:
#    name: ""
