apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    beta.cloud.google.com/backend-config: '{"ports": {"80":"nginx-backendconfig"}}'
spec:
  type: NodePort
  selector:
    app: go
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
