apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: blog
    tier: middle
spec:
  type: ClusterIP
  selector:
    app: blog
    tier: middle
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
