apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: blog
    tier: middle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
      tier: middle
  template:
    metadata:
      labels:
        app: blog
        tier: middle
    spec:
      initContainers:
      - name: mysql-connection-check
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c"]
        args:
          - |
            until mysqladmin ping -h $(DB_HOST) -u $(DB_USER) --password=$(DB_PASS) --silent; do
                echo 'waiting for mysqld to be connectable...'
                sleep 3
            done
        envFrom:
          - configMapRef:
              name: django-db-config
          - secretRef:
              name: mysql-db-pass
      containers:
      - name: django
        image: app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
          - name: DATADOG_APP_NAME
            value: "blog"
          - name: DATADOG_APP_ENV
            value: "development"
          - name: DATADOG_TRACE_AGENT_HOSTNAME
            value: "datadog-agent.datadog.svc.cluster.local"
          - name: DD_AGENT_PORT
            value: "8126"
        envFrom:
          - configMapRef:
              name: django-db-config
          - secretRef:
              name: mysql-db-pass
