apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: blog
    tier: middle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
      tier: middle
  template:
    metadata:
      labels:
        app: blog
        tier: middle
    spec:
      containers:
      - name: app
        image: asia.gcr.io/soe-trial-oota/app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: DATADOG_APP_NAME
            value: "blog"
          - name: DATADOG_APP_ENV
            value: "development"
          - name: DATADOG_TRACE_AGENT_HOSTNAME
            value: "datadog-agent.datadog.svc.cluster.local"
          - name: DD_AGENT_PORT
            value: "8126"
