apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# すべてのリソースに設定するnamespace
namespace: my-first-blog

# リソース名のprefix
#namePrefix: alices-

# すべてのリソースに追加するlabelとselector
commonLabels:
  app: my-first-blog

# すべてのリソースに追加するAnnotation
commonAnnotations:
  oncallPager: 800-555-1212

# kustomizeでビルドする対象ファイル
resources:
- ./deployment.yaml
- ./service.yaml
- ./namespace.yaml

# base
#bases:
#- ../../bases

images:
- name: asia.gcr.io/soe-gcp-development/my-first-blog
  newTag: latest
