apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: blog
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: blog
    tier: backend
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      name: tcp
