apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: blog
    tier: backend
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blog
        tier: backend
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: django-db-config
              key: DB_NAME
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: django-db-config
              key: DB_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-db-pass
              key: DB_PASS
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-db-pass
              key: DB_PASS
